import React from 'react'
import Header from './header'
import Head from 'next/head'
import Footer from './footer'

const Layout = (props) => {
  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className='m-8'>
            { props.children }
        </main>
        <Footer />
    </div>
  )
}

export default Layout